"""Seed data for NikahKita. Deterministic IDs so re-seeding is idempotent."""

IMG = {
    "venue1": "https://images.unsplash.com/photo-1724855946379-451f59d45df6?crop=entropy&cs=srgb&fm=jpg&q=85",
    "venue2": "https://images.unsplash.com/photo-1738225734899-30852be7e396?crop=entropy&cs=srgb&fm=jpg&q=85",
    "venue3": "https://images.unsplash.com/photo-1627818243473-acb731041bd5?crop=entropy&cs=srgb&fm=jpg&q=85",
    "cake": "https://images.unsplash.com/photo-1719512037487-78e399b58a53?crop=entropy&cs=srgb&fm=jpg&q=85",
    "siraman": "https://images.unsplash.com/photo-1623991614441-2b124385eb63?crop=entropy&cs=srgb&fm=jpg&q=85",
    "hero": "https://images.unsplash.com/photo-1650377509488-724221735c19?crop=entropy&cs=srgb&fm=jpg&q=85",
    "adat": "https://images.unsplash.com/photo-1650377509428-11e7fe8614a9?crop=entropy&cs=srgb&fm=jpg&q=85",
    "photo1": "https://images.unsplash.com/photo-1519741497674-611481863552?crop=entropy&cs=srgb&fm=jpg&q=85",
    "photo2": "https://images.unsplash.com/photo-1583939003579-730e3918a45a?crop=entropy&cs=srgb&fm=jpg&q=85",
    "catering": "https://images.unsplash.com/photo-1555244162-803834f70033?crop=entropy&cs=srgb&fm=jpg&q=85",
    "mua": "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?crop=entropy&cs=srgb&fm=jpg&q=85",
    "deco": "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?crop=entropy&cs=srgb&fm=jpg&q=85",
    "band": "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?crop=entropy&cs=srgb&fm=jpg&q=85",
}

CITIES = ["Jakarta", "Bandung", "Bali", "Yogyakarta", "Surabaya"]
CATEGORIES = ["Venue", "Fotografer", "Katering", "MUA", "Dekorasi", "Wedding Organizer", "Entertainment"]
ADAT = ["Jawa", "Sunda", "Bali", "Minang", "Batak", "Chinese", "Modern"]

def V(idx, name, cat, city, adat_tags, price_min, price_max, cover, cap_min=0, cap_max=0, tier="free",
      indoor="both", desc=""):
    slug = f"{name.lower().replace(' ', '-')}-{idx:03d}"
    return {
        "id": f"vendor-{idx:03d}",
        "slug": slug,
        "name": name,
        "category": cat,
        "subcategories": [],
        "city": city,
        "address": f"Jl. Melati No. {idx}, {city}",
        "description": desc or f"{name} adalah vendor {cat.lower()} tepercaya di {city}. Spesialisasi adat {', '.join(adat_tags)}.",
        "phone": f"+628123456{idx:04d}",
        "whatsapp": f"628123456{idx:04d}",
        "website": "",
        "cover_image": cover,
        "gallery": [cover, IMG["venue1"], IMG["venue2"], IMG["cake"], IMG["adat"]],
        "packages": [
            {"id": f"pkg-{idx}-1", "name": "Paket Silver", "price_idr": price_min, "dp_percent": 30,
             "inclusions": ["Konsultasi awal", "Setup venue", "Dokumentasi 4 jam"]},
            {"id": f"pkg-{idx}-2", "name": "Paket Gold", "price_idr": int((price_min + price_max) / 2), "dp_percent": 30,
             "inclusions": ["Semua paket Silver", "Dekorasi premium", "Tim lengkap"]},
            {"id": f"pkg-{idx}-3", "name": "Paket Platinum", "price_idr": price_max, "dp_percent": 50,
             "inclusions": ["Semua paket Gold", "Pre-wedding", "Album custom", "Prioritas vendor"]},
        ],
        "adat_tags": adat_tags,
        "indoor_outdoor": indoor,
        "capacity_min": cap_min,
        "capacity_max": cap_max,
        "price_min": price_min,
        "price_max": price_max,
        "tier": tier,
        "rating_avg": round(4.5 + (idx % 5) * 0.1, 1),
        "review_count": 8 + (idx % 20),
    }

SEED_VENDORS = [
    V(1, "Grand Hyatt Ballroom", "Venue", "Jakarta", ["Modern", "Chinese"], 150_000_000, 450_000_000, IMG["venue1"], 300, 1500, "premium", "indoor",
      "Grand Hyatt Ballroom menyediakan ruang pelaminan elegan di jantung Jakarta dengan kapasitas hingga 1500 tamu."),
    V(2, "Pullman Thamrin", "Venue", "Jakarta", ["Modern"], 120_000_000, 350_000_000, IMG["venue2"], 200, 1000, "featured", "indoor"),
    V(3, "The Mulia Resort Nusa Dua", "Venue", "Bali", ["Bali", "Modern"], 200_000_000, 800_000_000, IMG["venue3"], 150, 800, "premium", "both",
      "Resort tepi pantai dengan arsitektur Bali kontemporer, cocok untuk destination wedding."),
    V(4, "Trans Luxury Hotel Bandung", "Venue", "Bandung", ["Sunda", "Modern"], 80_000_000, 250_000_000, IMG["venue1"], 150, 800, "featured", "indoor"),
    V(5, "Royal Ambarrukmo Yogyakarta", "Venue", "Yogyakarta", ["Jawa"], 90_000_000, 280_000_000, IMG["venue2"], 200, 1200, "premium", "both",
      "Royal Ambarrukmo berdiri sejak era Keraton — pilihan utama untuk pernikahan adat Jawa klasik."),
    V(6, "Shangri-La Surabaya", "Venue", "Surabaya", ["Chinese", "Modern"], 100_000_000, 300_000_000, IMG["venue3"], 200, 1000, "featured", "indoor"),

    V(7, "Axioo Photography", "Fotografer", "Jakarta", ["Modern", "Chinese", "Jawa"], 25_000_000, 95_000_000, IMG["photo1"], tier="premium",
      desc="Studio dokumentasi dengan gaya editorial. Portofolio di lebih dari 20 kota."),
    V(8, "Antijitters", "Fotografer", "Jakarta", ["Modern"], 20_000_000, 60_000_000, IMG["photo2"], tier="featured"),
    V(9, "Thepotomoto", "Fotografer", "Bandung", ["Sunda", "Modern"], 15_000_000, 45_000_000, IMG["photo1"]),
    V(10, "Dreamcatcher Bali", "Fotografer", "Bali", ["Bali", "Modern"], 22_000_000, 70_000_000, IMG["photo2"], tier="featured",
       desc="Spesialis sunset beach wedding di Uluwatu dan Nusa Dua."),
    V(11, "Rendra Studio", "Fotografer", "Yogyakarta", ["Jawa"], 12_000_000, 35_000_000, IMG["photo1"]),

    V(12, "Akasya Catering", "Katering", "Jakarta", ["Jawa", "Sunda", "Modern"], 180_000, 450_000, IMG["catering"], cap_min=100, cap_max=3000, tier="premium",
       desc="Katering halal dengan menu nusantara dan international. Minimum 300 pax."),
    V(13, "Pesona Jasa Boga", "Katering", "Jakarta", ["Jawa", "Sunda"], 150_000, 350_000, IMG["catering"], cap_min=200, cap_max=2500, tier="featured"),
    V(14, "Nirwana Catering Bandung", "Katering", "Bandung", ["Sunda"], 125_000, 275_000, IMG["catering"], cap_min=150, cap_max=1500),
    V(15, "Bumbu Desa Catering", "Katering", "Bandung", ["Sunda", "Minang"], 135_000, 295_000, IMG["catering"], cap_min=200, cap_max=2000),
    V(16, "Rumah Makan Padang Sari", "Katering", "Jakarta", ["Minang"], 165_000, 285_000, IMG["catering"], cap_min=100, cap_max=1500,
       desc="Spesialis katering adat Minang dengan juru masak langsung dari Padang."),

    V(17, "Bennu Sorumba Makeup", "MUA", "Jakarta", ["Jawa", "Sunda", "Modern"], 15_000_000, 65_000_000, IMG["mua"], tier="premium",
       desc="Signature paes modifikasi dengan touch of modern glam."),
    V(18, "Adi Adrian MUA", "MUA", "Jakarta", ["Modern", "Chinese"], 12_000_000, 45_000_000, IMG["mua"], tier="featured"),
    V(19, "Rias Pengantin Paes Ageng Solo", "MUA", "Yogyakarta", ["Jawa"], 8_000_000, 25_000_000, IMG["mua"],
       desc="Rias pengantin Paes Ageng Solo klasik, pewaris keraton generasi ketiga."),
    V(20, "Bali Bride Makeup", "MUA", "Bali", ["Bali"], 10_000_000, 30_000_000, IMG["mua"]),
    V(21, "Minang Siang Suntiang", "MUA", "Jakarta", ["Minang"], 11_000_000, 32_000_000, IMG["mua"]),

    V(22, "Lotus Design", "Dekorasi", "Jakarta", ["Modern", "Chinese"], 50_000_000, 300_000_000, IMG["deco"], tier="premium",
       desc="Dekorasi modern-minimalis dan grand luxury untuk gedung dengan ceiling tinggi."),
    V(23, "Pelaminan Nusantara", "Dekorasi", "Jakarta", ["Jawa", "Sunda", "Minang", "Batak"], 40_000_000, 180_000_000, IMG["deco"], tier="featured",
       desc="Pelaminan adat lengkap dari 7 daerah di Indonesia."),
    V(24, "Suryadi Dekorasi Yogyakarta", "Dekorasi", "Yogyakarta", ["Jawa"], 25_000_000, 95_000_000, IMG["deco"]),
    V(25, "Flora Bali Decoration", "Dekorasi", "Bali", ["Bali", "Modern"], 35_000_000, 150_000_000, IMG["deco"]),

    V(26, "The Wedding Alchemist", "Wedding Organizer", "Jakarta", ["Modern", "Chinese", "Jawa"], 25_000_000, 120_000_000, IMG["venue1"], tier="premium"),
    V(27, "Mahardhika WO", "Wedding Organizer", "Jakarta", ["Jawa", "Sunda"], 18_000_000, 65_000_000, IMG["venue2"], tier="featured"),
    V(28, "Rumah Nikah Bandung", "Wedding Organizer", "Bandung", ["Sunda", "Modern"], 15_000_000, 55_000_000, IMG["venue1"]),

    V(29, "Soundwave Entertainment", "Entertainment", "Jakarta", ["Modern"], 15_000_000, 85_000_000, IMG["band"], tier="featured",
       desc="Live band, string quartet, DJ, dan MC bilingual."),
    V(30, "Jazz Up Band", "Entertainment", "Bandung", ["Modern"], 12_000_000, 45_000_000, IMG["band"]),
    V(31, "Gamelan Keraton", "Entertainment", "Yogyakarta", ["Jawa"], 10_000_000, 35_000_000, IMG["band"],
       desc="Gamelan Jawa lengkap untuk prosesi akad dan siraman."),
    V(32, "Angklung Mang Udjo", "Entertainment", "Bandung", ["Sunda"], 8_000_000, 25_000_000, IMG["band"]),
]

SEED_REAL_WEDDINGS = [
    {
        "id": "rw-001",
        "slug": "andini-raka-jawa-yogyakarta",
        "couple_names": "Andini & Raka",
        "city": "Yogyakarta",
        "adat": "Jawa",
        "guest_count": 1200,
        "cover_image": IMG["adat"],
        "story": "Andini dan Raka merayakan pernikahan dengan prosesi Jawa klasik lengkap: siraman, midodareni, akad, hingga panggih. Resepsi digelar di Royal Ambarrukmo dengan dekorasi Paes Ageng.",
        "gallery": [IMG["adat"], IMG["siraman"], IMG["venue2"], IMG["cake"], IMG["mua"], IMG["deco"]],
        "vendor_credits": [
            {"category": "Venue", "name": "Royal Ambarrukmo Yogyakarta", "vendor_id": "vendor-005"},
            {"category": "MUA", "name": "Rias Pengantin Paes Ageng Solo", "vendor_id": "vendor-019"},
            {"category": "Fotografer", "name": "Rendra Studio", "vendor_id": "vendor-011"},
        ],
    },
    {
        "id": "rw-002",
        "slug": "clarissa-timothy-chinese-jakarta",
        "couple_names": "Clarissa & Timothy",
        "city": "Jakarta",
        "adat": "Chinese",
        "guest_count": 800,
        "cover_image": IMG["venue1"],
        "story": "Prosesi Teapai pagi di rumah dilanjutkan resepsi grand ballroom di Grand Hyatt dengan dekorasi merah-emas modern.",
        "gallery": [IMG["venue1"], IMG["cake"], IMG["mua"], IMG["deco"], IMG["photo1"]],
        "vendor_credits": [
            {"category": "Venue", "name": "Grand Hyatt Ballroom", "vendor_id": "vendor-001"},
            {"category": "Fotografer", "name": "Axioo Photography", "vendor_id": "vendor-007"},
            {"category": "Dekorasi", "name": "Lotus Design", "vendor_id": "vendor-022"},
        ],
    },
    {
        "id": "rw-003",
        "slug": "made-putri-bali-uluwatu",
        "couple_names": "Made & Putri",
        "city": "Bali",
        "adat": "Bali",
        "guest_count": 150,
        "cover_image": IMG["venue3"],
        "story": "Destination wedding intim di tebing Uluwatu dengan prosesi Payas Agung dan sunset dinner.",
        "gallery": [IMG["venue3"], IMG["adat"], IMG["mua"], IMG["photo2"]],
        "vendor_credits": [
            {"category": "Venue", "name": "The Mulia Resort Nusa Dua", "vendor_id": "vendor-003"},
            {"category": "Fotografer", "name": "Dreamcatcher Bali", "vendor_id": "vendor-010"},
            {"category": "MUA", "name": "Bali Bride Makeup", "vendor_id": "vendor-020"},
        ],
    },
    {
        "id": "rw-004",
        "slug": "siti-fajar-minang-jakarta",
        "couple_names": "Siti & Fajar",
        "city": "Jakarta",
        "adat": "Minang",
        "guest_count": 1500,
        "cover_image": IMG["mua"],
        "story": "Pernikahan Minang lengkap dengan Suntiang 11 tingkat, baralek gadang di JCC Senayan.",
        "gallery": [IMG["mua"], IMG["catering"], IMG["deco"]],
        "vendor_credits": [
            {"category": "MUA", "name": "Minang Siang Suntiang", "vendor_id": "vendor-021"},
            {"category": "Katering", "name": "Rumah Makan Padang Sari", "vendor_id": "vendor-016"},
        ],
    },
    {
        "id": "rw-005",
        "slug": "mira-dion-sunda-bandung",
        "couple_names": "Mira & Dion",
        "city": "Bandung",
        "adat": "Sunda",
        "guest_count": 600,
        "cover_image": IMG["venue1"],
        "story": "Siraman di rumah Bandung dengan Sawer dan Huap Lingkung, resepsi Sundanese modern di Trans Hotel.",
        "gallery": [IMG["venue1"], IMG["siraman"], IMG["deco"]],
        "vendor_credits": [
            {"category": "Venue", "name": "Trans Luxury Hotel Bandung", "vendor_id": "vendor-004"},
            {"category": "Fotografer", "name": "Thepotomoto", "vendor_id": "vendor-009"},
        ],
    },
    {
        "id": "rw-006",
        "slug": "nadia-arif-modern-jakarta",
        "couple_names": "Nadia & Arif",
        "city": "Jakarta",
        "adat": "Modern",
        "guest_count": 400,
        "cover_image": IMG["venue2"],
        "story": "Intimate modern wedding di Pullman Thamrin dengan tema all-white dan monokrom.",
        "gallery": [IMG["venue2"], IMG["cake"], IMG["photo1"]],
        "vendor_credits": [
            {"category": "Venue", "name": "Pullman Thamrin", "vendor_id": "vendor-002"},
            {"category": "Fotografer", "name": "Antijitters", "vendor_id": "vendor-008"},
        ],
    },
    {
        "id": "rw-007",
        "slug": "ruth-ben-batak-medan",
        "couple_names": "Ruth & Ben",
        "city": "Jakarta",
        "adat": "Batak",
        "guest_count": 900,
        "cover_image": IMG["adat"],
        "story": "Pesta Adat Batak Mandailing dengan upa-upa dan ulos pargomgom.",
        "gallery": [IMG["adat"], IMG["catering"]],
        "vendor_credits": [
            {"category": "Dekorasi", "name": "Pelaminan Nusantara", "vendor_id": "vendor-023"},
        ],
    },
    {
        "id": "rw-008",
        "slug": "ayla-rendra-garden-bogor",
        "couple_names": "Ayla & Rendra",
        "city": "Jakarta",
        "adat": "Modern",
        "guest_count": 300,
        "cover_image": IMG["venue3"],
        "story": "Garden wedding dengan tema pastel dan nuansa Eropa.",
        "gallery": [IMG["venue3"], IMG["deco"], IMG["cake"]],
        "vendor_credits": [],
    },
    {
        "id": "rw-009",
        "slug": "indira-bram-chinese-surabaya",
        "couple_names": "Indira & Bram",
        "city": "Surabaya",
        "adat": "Chinese",
        "guest_count": 700,
        "cover_image": IMG["venue3"],
        "story": "Teapai pagi lanjut grand ballroom Shangri-La Surabaya.",
        "gallery": [IMG["venue3"], IMG["photo2"]],
        "vendor_credits": [
            {"category": "Venue", "name": "Shangri-La Surabaya", "vendor_id": "vendor-006"},
        ],
    },
    {
        "id": "rw-010",
        "slug": "kiara-dani-bali-ubud",
        "couple_names": "Kiara & Dani",
        "city": "Bali",
        "adat": "Bali",
        "guest_count": 100,
        "cover_image": IMG["adat"],
        "story": "Pernikahan adat Bali di Ubud, dilanjutkan dengan elopement photoshoot di rice terrace.",
        "gallery": [IMG["adat"], IMG["mua"], IMG["venue3"]],
        "vendor_credits": [
            {"category": "MUA", "name": "Bali Bride Makeup", "vendor_id": "vendor-020"},
        ],
    },
]

SEED_REVIEWS = [
    {"id": "rev-001", "vendor_id": "vendor-001", "user_id": "seed", "user_name": "Dewi A.", "rating": 5,
     "title": "Pelayanan impeccable", "body": "Tim banquet Grand Hyatt sangat profesional. Semua rundown jalan on time."},
    {"id": "rev-002", "vendor_id": "vendor-001", "user_id": "seed", "user_name": "Rahmat S.", "rating": 5,
     "title": "Worth every rupiah", "body": "Harga premium tapi delivery sesuai. Food quality top."},
    {"id": "rev-003", "vendor_id": "vendor-007", "user_id": "seed", "user_name": "Lia P.", "rating": 5,
     "title": "Hasil foto editorial banget", "body": "Axioo tangkap momen candid dengan sangat natural. Album custom bagus banget."},
    {"id": "rev-004", "vendor_id": "vendor-010", "user_id": "seed", "user_name": "Made K.", "rating": 5,
     "title": "Sunset wedding masterpiece", "body": "Dreamcatcher Bali hasilnya cinematic banget, feels like a film."},
    {"id": "rev-005", "vendor_id": "vendor-017", "user_id": "seed", "user_name": "Anya W.", "rating": 5,
     "title": "Rias tahan 12 jam", "body": "Make up Bennu tahan dari akad sampai resepsi malam. Highly recommend."},
    {"id": "rev-006", "vendor_id": "vendor-019", "user_id": "seed", "user_name": "Puspita H.", "rating": 5,
     "title": "Paes Ageng autentik", "body": "Beliau sabar dan telaten. Hasil riasan sesuai pakem Keraton Solo."},
    {"id": "rev-007", "vendor_id": "vendor-012", "user_id": "seed", "user_name": "Fitri L.", "rating": 4,
     "title": "Rasa oke, logistik rapi", "body": "Akasya rasa makanan konsisten dari tasting ke hari H."},
]
